### ISSUE TITLE
Update job broken the past few weeks

### ISSUE THREAD

**Issue by abathur** [nix-community/nix-unstable-installer#55]
Came to see if there was an unstable installer with a recently-merged fix for someone having install trouble and noticed it hasn't generated in a few weeks.

**Comment by lilyinstarlight** [comment]
It looks like there haven't been Hydra evals which have all builds and test jobs succeed for a long while... (<https://hydra.nixos.org/job/nix/master/tests.setuid.i686-linux/all> in particular has been failing for a while) The only reason the update job fails is because it can't find *any* good builds anymore since the number of evals it checks is capped

I'll probably adjust the script to exclude that one failing job for now since it seems to be failing for unrelated reasons and is i686-linux, which I really don't care for anyway
